<!DOCTYPE html>
    <html>
    <head>
        <title></title>
        <style>
            body { font-family: 'Courier New', monospace; font-size: 12px; background-color: #000; color: #0f0; }
            #ascii-container { white-space: pre; }
        </style>
    </head>
    <body>
        <div id="ascii-container"></div>
        <script src="animation.js"></script>
    </body>
    </html>
